### ISSUE TITLE
Error when training the text encoder DAMSM

### ISSUE THREAD

**Issue by ghost** [humanist-bean/hungry_ai#1]
Hello @humanist-bean, thanks for your work, do you have a problem with training the text encoder DAMSM in the [Style-AttnGAN repo](https://github.com/sidward14/Style-AttnGAN/tree/master), I follow the same steps to train but I got this error:
```
File "Style-AttnGAN\code\datasets.py", line 87, in get_imgs

re_img = transforms.Resize(imsize[i])(img)
IndexError: list index out of range
```

I don't know what the problem is, do you know how to fix this error ? Thanks for your help !

**Comment by french-fryy** [comment]
Good evening @VeryIdiotUser, it looks like the problem has something to do with the imsize[] array being accessed out of bounds. Can you show me the code where you set i and imsize? Then i might get a better idea of what's going on.

**Comment by ghost** [comment]
Hi @humanist-bean, thanks for your response, I downloaded the code from the [Style-AttnGAN repo](https://github.com/sidward14/Style-AttnGAN) and I haven't made any changes to the code. I wanted to train the text encoder DAMSM using the bird dataset before training it with your dataset. However, I encountered an error mention above while trying to train it. I followed the instructions for setting up the dataset, but I'm not sure why it's keeps throwing error.

I would really appreciate your help in resolving this issue. Thank you so much.

**Comment by ghost** [comment]
I asked you because I noticed two files in your `code/Style-AttnGAN` folder: `datasets.py` and `datasets_bad.py`. I see that you made modifications to the code in [datasets_bad.py](https://github.com/humanist-bean/hungry_ai/blob/e7eca0cca93daf3bdbfedf5ad0ca70ed22c917c6/code/Style-AttnGAN-master/code/datasets_bad.py#L91C9-L91C9), which suggests that you may have encountered the same issue when training DAMSM initially. So, I wanted to ask if you were able to train successfully.

**Comment by french-fryy** [comment]
Hello again @VeryIdiotUser, while I was able to eventually train a text encoder and generator for my food project, upon further inspection I am remembering that this codebase is a bit of a mess. I have not yet set it up to work very easily for other projects. If you want to get it to working you will have to reverse engineer it, you can start by looking at this file code/Style-AttnGAN-master/code/cfg/barebones_bird_attn2_style.yml. I may come back and clean it up later but at the moment I am busy working on another project. I'm going through the code again, if I see anything else thats helpful I will let you know.

**Comment by french-fryy** [comment]
Alright @VeryIdiotUser, here's the scoop. After further examining my code, it looks like there is a trail of breadcrumbs one could follow to copy what I did, even with a different dataset. First, you need to create your own DAMSM text to image encoder using this repo: https://github.com/sidward14/Style-AttnGAN . If I remember correctly this encoder is trained with pictures of images and their captions. Then you might be able to follow along with the steps I took to use the encoder with the SSAGAN model by looking at my jupiter notebook that outlines the process: https://github.com/humanist-bean/hungry_ai/blob/master/code/text2image-alder/hungry_ai.ipynb . To be honest doing all this would require a lot of work, it would be cool if I came back and made a pipeline to do all this with a script in the future, but I'm busy looking for a job right now and working on other projects so that could take a while. Good luck!

**Comment by ghost** [comment]
I'm actually trying to train the DAMSM in the repo: https://github.com/sidward14/Style-AttnGAN using the bird dataset (from the author too), but I keeps encounter the error above, that error has been discussed in here: https://github.com/taoxugit/AttnGAN/issues/92 but it seems like there is no solution to fix, thanks for your answer.
